Repository hakkutu-za/project-jaguar, pull requests merged in 2020-06, with the labels that each got.

#8 Added env variables for grafana certs
  docker-compose.yml
Labels: enhancement

#9 Developer
  certs/home.crt
  certs/home.key
  docker-compose.yml
Labels: enhancement

#10 New secrets file with a htpasswd, nginx directory with nginx conf fil…
  docker-compose.yml
  nginx/nginx.conf
  nginx/nginx.conf-backup
  secrets/htpasswd
Labels: enhancement

#11 Removed the IPs and used the container names on nginx file
  nginx.conf
  nginx/nginx.conf
Labels: enhancement, invalid

#12 Use relative path to the root of the project for the nginx config map…
  docker-compose.yml
Labels: bug

#13 Removed deploy key from cadvisor and node_exporter as it is a propert…
  docker-compose.yml
Labels: improvement
